#!/bin/sh

target=DOCKER-USER
chain=DOCKER-USER-COUNTRY
deny=${FW_DENY:-REJECT}
[ "$deny" = "REJECT" ] && deny="REJECT --reject-with icmp-port-unreachable"

IF=$(ip route | awk '/^default/{print $5}')

echo "# Generated by iptables.sh on $(date)"
echo "# Public interface: $IF"
iptables-save -t filter | sed "/$chain/d;/^COMMIT$/d;/^#/d"

# Allow the firewall to be disabled
if [[ "$FW_DISABLE" = "1" ]]; then
  echo COMMIT
  echo "# Removed all country-blocking rules"
  exit 0
fi

# Add new chain and populate from downloaded file(s)
echo -N ${chain}

if [[ "$USE_IPSET" = "1" ]]; then
  i=0
  for f in /zones/*.zone; do
    name="${f#*/zones/}"
    name="${name%.zone}"
    echo -A ${chain} -m set --match-set country_$name src -j $deny
    ipset -L country_$name >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      ipset -N country_$name hash:net
    else
      ipset flush country_$name
    fi
    while read cidr; do
      ipset -A country_$name $cidr
      i=$((i+1))
    done < $f
  done
else
  i=0
  for f in /zones/*.zone; do
    while read cidr; do
      echo -A ${chain} -s $cidr -j $deny
      i=$((i+1))
    done < $f
  done
fi
echo -A ${chain} -j RETURN

# Insert rule into DOCKER-USER
echo -I $target -i $IF -p all -j ${chain}

echo COMMIT
echo "# Added $i country-blocking rules"
